### ISSUE TITLE
svg folder woudnt be linked

### ISSUE THREAD

**Issue by strech345** [fxi/svgToSprite#1]
i run this command on windows
`docker run -it --rm -v C:\Users\<myuser>\repos\svgToSprite\dist:/dist -v C:\Users\pst.ENERSIS\repos\svgToSprite\svg:/svg fredmoser/svg_to_sprite:latest`

and also without `-itt --rm`

but dist link workes! i get the result into my windows folder
but i coudnt get the svg folder include

**Comment by fxi** [comment]
Thanks for reporting this.
Can you try with the latest image ? I just pushed a change.

**Comment by strech345** [comment]
yes thanks. looks good

**Comment by fxi** [comment]
So, I close this.
